###login
POST http://localhost:3003/users/login 
Content-Type: application/json

{
    "email":"teste01@gmail.com",
    "password":"123456"
}

### sign up

POST http://localhost:3003/users/sign
Content-Type: application/json

{
    "name":"teste02",
    "email":"teste02@gmail.com",
    "password":"1256"
}

### get all users

GET http://localhost:3003/users/allUsers
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGFjOTA1LTRiODktNGFmZi1iZTQ4LWIxMDFhOGViNzBkOSIsImlhdCI6MTY3NjQxMzc0NCwiZXhwIjoxNjc2NDM1MzQ0fQ.iL0XEWrWDi-iNA6z-M5sg9u1SZ1pYvGYqtwss3VbqYU


### GET PROFILE 

GET http://localhost:3003/users/profile
Content-Type: application/json
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGFjOTA1LTRiODktNGFmZi1iZTQ4LWIxMDFhOGViNzBkOSIsImlhdCI6MTY3NjQxODQyOCwiZXhwIjoxNjc2NDQwMDI4fQ.XJmCskb8xBvBUu_TtbGujNCUquwJIhHrhHwsnzsnafY